# Generated by Django 6.0.3 on 2026-04-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_useraddress_userpaymentmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("MANAGER", "Manager"),
                    ("ADMIN_SUPER", "Super"),
                    ("ADMIN_EDITOR", "Editor"),
                    ("ADMIN_SUPPORT", "Support"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
