# Generated by Django 4.2.24 on 2026-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("EMPLOYEE", "Employee"),
                    ("MANAGER", "Manager"),
                    ("ADMIN_SUPER", "Super"),
                    ("ADMIN_EDITOR", "Editor"),
                    ("ADMIN_SUPPORT", "Support"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
