# Generated by Django 4.2.24 on 2026-05-05 06:37

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="avatar_url",
        ),
        migrations.AddField(
            model_name="staff",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=utils.helpers.imageUploadHelper
            ),
        ),
    ]
