# Generated by Django 6.0.4 on 2026-05-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0002_remove_staff_avatar_url_staff_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
